"""llm_mesh

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-01 07:59:33.243267

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quota_reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scope_type", sa.String(length=20), nullable=False),
        sa.Column("scope_id", sa.UUID(), nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("estimated_micros", sa.BigInteger(), nullable=False),
        sa.Column("settled_micros", sa.BigInteger(), nullable=True),
        sa.Column("call_id", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quota_reservations")),
    )
    op.create_index(
        "ix_quota_reservations_scope_ts",
        "quota_reservations",
        ["scope_type", "scope_id", "ts"],
        unique=False,
    )
    op.create_table(
        "quotas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scope_type", sa.String(length=20), nullable=False),
        sa.Column("scope_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.String(length=10), nullable=False),
        sa.Column("limit_cost_micros", sa.BigInteger(), nullable=True),
        sa.Column("limit_calls", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("action IN ('warn', 'block')", name=op.f("ck_quotas_action")),
        sa.CheckConstraint("period IN ('day', 'month')", name=op.f("ck_quotas_period")),
        sa.CheckConstraint(
            "scope_type IN ('project', 'user', 'connection', 'agent')",
            name=op.f("ck_quotas_scope_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotas")),
        sa.UniqueConstraint("scope_type", "scope_id", "period", name="uq_quotas_scope_period"),
    )
    op.create_table(
        "guardrail_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "stages",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_guardrail_policies_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guardrail_policies")),
        sa.UniqueConstraint("project_id", "name", name="uq_guardrail_policies_project_name"),
    )
    op.create_index(
        op.f("ix_guardrail_policies_project_id"), "guardrail_policies", ["project_id"], unique=False
    )
    op.create_table(
        "prompts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column(
            "variables",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "model_defaults",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.String(length=50)),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_prompts_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_prompts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompts")),
        sa.UniqueConstraint(
            "project_id", "name", "version", name="uq_prompts_project_name_version"
        ),
    )
    op.create_index(op.f("ix_prompts_project_id"), "prompts", ["project_id"], unique=False)
    op.create_table(
        "traces",
        sa.Column("trace_id", sa.UUID(), nullable=False),
        sa.Column("root_kind", sa.String(length=20), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("agent_version_id", sa.UUID(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("total_cost_micros", sa.BigInteger(), nullable=False),
        sa.Column("span_count", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "root_kind IN ('agent', 'recipe', 'chat', 'eval', 'semantic', 'manual')",
            name=op.f("ck_traces_root_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_traces_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("trace_id", name=op.f("pk_traces")),
    )
    op.create_index(op.f("ix_traces_project_id"), "traces", ["project_id"], unique=False)
    op.create_table(
        "llm_connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column(
            "base_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "allowed_models",
            postgresql.ARRAY(sa.String(length=200)),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("secret_id", sa.UUID(), nullable=True),
        sa.Column("guardrail_policy_id", sa.UUID(), nullable=True),
        sa.Column("cache_ttl_s", sa.Integer(), nullable=False),
        sa.Column("audit_mode", sa.String(length=16), nullable=False),
        sa.Column("data_residency", sa.String(length=16), nullable=False),
        sa.Column("legal_basis", sa.String(length=500), nullable=False),
        sa.Column("purpose_codes", postgresql.ARRAY(sa.String(length=100)), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'global' AND project_id IS NULL) OR (scope = 'project' AND project_id IS NOT NULL)",
            name=op.f("ck_llm_connections_scope_project"),
        ),
        sa.CheckConstraint(
            "audit_mode IN ('full', 'redacted', 'off')", name=op.f("ck_llm_connections_audit_mode")
        ),
        sa.CheckConstraint(
            "data_residency IN ('local', 'eu', 'external')",
            name=op.f("ck_llm_connections_data_residency"),
        ),
        sa.CheckConstraint(
            "provider IN ('echo', 'openai', 'anthropic', 'ollama')",
            name=op.f("ck_llm_connections_provider"),
        ),
        sa.CheckConstraint("scope IN ('global', 'project')", name=op.f("ck_llm_connections_scope")),
        sa.CheckConstraint(
            "status IN ('active', 'archived')", name=op.f("ck_llm_connections_status")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_llm_connections_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["guardrail_policy_id"],
            ["guardrail_policies.id"],
            name=op.f("fk_llm_connections_guardrail_policy_id_guardrail_policies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_llm_connections_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["secret_id"],
            ["secrets.id"],
            name=op.f("fk_llm_connections_secret_id_secrets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_connections")),
        sa.UniqueConstraint("project_id", "name", name="uq_llm_connections_project_name"),
    )
    op.create_index(
        op.f("ix_llm_connections_project_id"), "llm_connections", ["project_id"], unique=False
    )
    op.create_table(
        "spans",
        sa.Column("span_id", sa.UUID(), nullable=False),
        sa.Column("trace_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("input_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.Column("cost_micros", sa.BigInteger(), nullable=True),
        sa.Column("t0", sa.DateTime(timezone=True), nullable=False),
        sa.Column("t1", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "kind IN ('llm', 'tool', 'retrieval', 'guardrail', 'agent', 'plan', 'recipe')",
            name=op.f("ck_spans_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["trace_id"],
            ["traces.trace_id"],
            name=op.f("fk_spans_trace_id_traces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("span_id", name=op.f("pk_spans")),
    )
    op.create_index("ix_spans_trace", "spans", ["trace_id", "t0"], unique=False)
    op.create_table(
        "llm_cache",
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("response_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["llm_connections.id"],
            name=op.f("fk_llm_cache_connection_id_llm_connections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("request_hash", name=op.f("pk_llm_cache")),
    )
    op.create_index(op.f("ix_llm_cache_expires_at"), "llm_cache", ["expires_at"], unique=False)
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("trace_id", sa.UUID(), nullable=True),
        sa.Column("span_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("job_step_id", sa.UUID(), nullable=True),
        sa.Column("row_key", sa.String(length=255), nullable=True),
        sa.Column("connection_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("model_version", sa.String(length=200), nullable=True),
        sa.Column("purpose", sa.String(length=50), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("tokens_estimated", sa.Boolean(), nullable=False),
        sa.Column("cost_micros", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("pricing_unknown", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("guardrail_events_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["llm_connections.id"],
            name=op.f("fk_llm_calls_connection_id_llm_connections"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_llm_calls_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_llm_calls_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
    )
    op.create_index("ix_llm_calls_job", "llm_calls", ["job_id"], unique=False)
    op.create_index("ix_llm_calls_project_ts", "llm_calls", ["project_id", "ts"], unique=False)
    op.create_index("ix_llm_calls_trace", "llm_calls", ["trace_id"], unique=False)
    op.create_table(
        "guardrail_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("call_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("rule", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["llm_calls.id"],
            name=op.f("fk_guardrail_events_call_id_llm_calls"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guardrail_events")),
    )
    op.create_index(
        op.f("ix_guardrail_events_call_id"), "guardrail_events", ["call_id"], unique=False
    )
    op.create_table(
        "llm_call_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("call_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content_redacted", sa.Text(), nullable=False),
        sa.Column("content_raw", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["llm_calls.id"],
            name=op.f("fk_llm_call_messages_call_id_llm_calls"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_call_messages")),
        sa.UniqueConstraint("call_id", "seq", name="uq_llm_call_messages_call_seq"),
    )
    op.create_index(
        op.f("ix_llm_call_messages_call_id"), "llm_call_messages", ["call_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_call_messages_call_id"), table_name="llm_call_messages")
    op.drop_table("llm_call_messages")
    op.drop_index(op.f("ix_guardrail_events_call_id"), table_name="guardrail_events")
    op.drop_table("guardrail_events")
    op.drop_index("ix_llm_calls_trace", table_name="llm_calls")
    op.drop_index("ix_llm_calls_project_ts", table_name="llm_calls")
    op.drop_index("ix_llm_calls_job", table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_index(op.f("ix_llm_cache_expires_at"), table_name="llm_cache")
    op.drop_table("llm_cache")
    op.drop_index("ix_spans_trace", table_name="spans")
    op.drop_table("spans")
    op.drop_index(op.f("ix_llm_connections_project_id"), table_name="llm_connections")
    op.drop_table("llm_connections")
    op.drop_index(op.f("ix_traces_project_id"), table_name="traces")
    op.drop_table("traces")
    op.drop_index(op.f("ix_prompts_project_id"), table_name="prompts")
    op.drop_table("prompts")
    op.drop_index(op.f("ix_guardrail_policies_project_id"), table_name="guardrail_policies")
    op.drop_table("guardrail_policies")
    op.drop_table("quotas")
    op.drop_index("ix_quota_reservations_scope_ts", table_name="quota_reservations")
    op.drop_table("quota_reservations")
    # ### end Alembic commands ###
